travis:
  secure:
    BINSTAR_TOKEN: gIR0NPZ5iJq6k2vzCeoEK7xHYMPB0Ewi9rP6bUfxxhoRThh5hmoDLbgdAI+aj7jAqxoEjdeN12UhyQ32qhqXSnt6C/LUWTUQ29rp2n6S3Wx5EsHnUATgUgza4exJ1Qf3pIi/TVXeGrOrb+BQ+pJjZ6XIiQ4T1dggvtQ7jrW1mdr7q2wu0MywobBUD3X52O3CHRGhLPnastbRVJBueDj8aNhGpQ9sDFxHXR3EViHnPgRX9O156xLPz/wfbhsv1i0fZPSQSdmjH2oUSiT0jpEqIxGc4055s9waDKERCAER+IXxPyrE+xwZ6tEriGijyse53BuvEbf07qLbaqNS3rhdL7gjGSoUrcqsoMnZTa+GBi3cIDeGC1kdklHld253JJjnz0x2JsqftkBVZ98C0SDvuLRe822nUTVmZ0kzEo2yjjNDsDW911rS4PYm/nIMKuXMtvP8XJ7r0NOZ5yRQOkv3UXlUMLr7R4Oh0M/Pbg42p7+83j2sRuspltZG4+FaXypoVVGCeDRe0IaqfHe9OASL3CF0qbXgyMjWJ+4k6Yvz/+k7LXUcLRr/IQbP1I9bUuSGa3HZQMsx9KM/TgEthbhja+IeK6VUpDdidUidtOLQzCqrSLszt1zeCqa5rTF94FynsOkbXwX5TtmmhMVOmAOdjmGE5wQ/y1E3OeTKY1k9jgs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
